### ISSUE TITLE
An issue during add-on activation

### ISSUE THREAD

**Issue by micke3d** [gandalf3/auto-reload-linked-libraries#2]
<img width="759" alt="Screenshot_10" src="https://user-images.githubusercontent.com/64898305/108761869-b1c0c980-754f-11eb-9aa2-7dc1609a35e4.png">

**Comment by micke3d** [comment]
Hi! Thanks for this cool add-on but when I try to activate, appear this message.

I'm not a coder so I don't know what I can doing.

**Comment by kitt-cat** [comment]
@micke3d Ah, sorry! Did you install the zip from the [releases page](https://github.com/gandalf3/auto-reload-linked-libraries/releases/)? The addon depends on the `watchdog` module which should be bundled in the zip release.
