### ISSUE TITLE
Addon does not work

### ISSUE THREAD

**Issue by goblincobold** [gandalf3/auto-reload-linked-libraries#3]
I installed the addon but it doesn't work. Object information is not automatically updated.

**Comment by kitt-cat** [comment]
Hi! Thanks for the report! I'm happy to investigate, but just fair warning I have exams right now and it might be a few days before I can check it out.

In the meantime, if you want, perhaps you could post the output from the system console window (window > toggle system console), if there is any? Thanks! Incidentally, what version of Blender are you using? Thanks again, sorry for the inconvenience!

**Comment by goblincobold** [comment]
Blender 2.92.   System console not show report.

**Comment by kitt-cat** [comment]
Hi, sorry for the delay! I've released a new improved version, if you're still interested, you can find it here: https://github.com/gandalf3/auto-reload-linked-libraries/releases/tag/v1.0.0

**Comment by goblincobold** [comment]
Nice work!! The addon works.
