### ISSUE TITLE
Updates without losing materials and modifiers

### ISSUE THREAD

**Issue by ZiadJ** [gandalf3/auto-reload-linked-libraries#4]
Would it be possible to preserve the Blender changes after an update by reassigning the materials and modifiers assigned to each object in the hierarchy by name?

It would have to be imported rather than linked, however, in order to allow changes on the model.

**Comment by kitt-cat** [comment]
hey sorry i missed this! not sure i follow.. to modify the linked data locally you can in theory use a [library override](https://docs.blender.org/manual/en/latest/files/linked_libraries/library_overrides.html). does that not work for your use case?
