### ISSUE TITLE
Nested linked collections causes Blender to freeze

### ISSUE THREAD

**Issue by AlexisJonsson** [gandalf3/auto-reload-linked-libraries#5]
I have several linked collections that contain linked objects and other linked collections. They're all assets in a library I have set up.

Blender completely freezes after dragging in a few collections.

**Comment by AlexisJonsson** [comment]
Probably worth noting that they're all using linked materials as well and none of the files are large or dense with detail.

**Comment by kitt-cat** [comment]
Would it be possible to upload stripped-down or reconstructed example which exhibits this behavior? I'd be happy to take a look!

**Comment by AlexisJonsson** [comment]
Oh awesome! I'll throw together a little example setup with repro steps.

**Comment by AlexisJonsson** [comment]
Okay there we go, I was able to replicate the bug.

So this is an asset library I've set up that has objects, materials and rooms that are being linked together. (Using Blender 3.5.1)
[linked_asset_library.zip](https://github.com/gandalf3/auto-reload-linked-libraries/files/11780899/linked_asset_library.zip)

This example is set up to live in: "C:\linked_asset_library" for the links to work so make sure to set up a library with the settings from the picture.
![Screenshot 2023-06-18 022746](https://github.com/gandalf3/auto-reload-linked-libraries/assets/23642164/241b37d7-0384-4793-92d7-020dbd55f9bd)

To experience the freeze you open "C:\linked_asset_library\levels\level_01.blend" and drag in room_06 from the asset browser.

**Comment by kitt-cat** [comment]
Hello again, sorry for the delay. In spite of your stellar example (thank you!) I wasn't able to reproduce the same hang, but I think I found the cause of it anyway. Could you try this version?

Changes: https://github.com/gandalf3/auto-reload-linked-libraries/commit/4f84492dff3560bb100a4f7d088794a7aad4533b
Zip: [auto_reload_libraries.zip](https://github.com/gandalf3/auto-reload-linked-libraries/files/11813839/auto_reload_libraries.zip)

Please let me know if anything seems amiss!

**Comment by AlexisJonsson** [comment]
No worries, sorry for my delay too, was busy but just got home. I think that change fixed it! I can't get it to crash anymore.

**Comment by kitt-cat** [comment]
Yay! so glad to hear it!

I created a new tagged release, nothing is functionally different than the version in my comment above, but if you are inclined you can download it [from the release page](https://github.com/gandalf3/auto-reload-linked-libraries/releases).

Thanks again for the report!
